version: '3.8'

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/server.pem:/etc/ssl/server.pem
      - ./ssl/server.key:/etc/ssl/server.key
      - ./nginx/nginx.sh:/etc/service/nginx/run
      - ./src:/var/www/html/public
    depends_on:
      - php
    command: ["/etc/service/nginx/run"]
      
  php:
    build: .
    container_name: php
    volumes:
      - ./php/src:/var/www/html/public
    expose:
      - "9000"
